__author__ = 'toure'
"""
**TCB_Tool**

1. Test Translator - function which will interface with the test repository and collect the described functional logic
                     to construct an executable method.
2. Test Runner - construct which describes the overall framework which makes up majority of the TCB_Tool, that is
                 responsible for executing the logic generated by the translation layer.
3. Test Reporting - function which will be triggered by the test runner on success and is responsible for updating test
                    repositories and bug tracking infrastructure.
"""
